Remove mypy errors: re.search() might return None
Before this commit, `mypy raiden/transfer/mediated_transfer/target.py
--ignore-missing-imports` returned error messages:

```
raiden/utils/__init__.py:46: error: Item "None" of "Optional[Match[str]]" has no attribute "groups"
raiden/utils/__init__.py:52: error: Item "None" of "Optional[Match[str]]" has no attribute "groups"
```

This commit removes these errors.

This change is one step for
https://github.com/raiden-network/raiden/issues/3040.